power_data <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date in ('1/2/2007','2/2/2007')", sep = ";")
power_table = data.table(power_data)
power_table$DateTime <- as.POSIXct( strptime(paste(power_table$Date, power_table$Time), format="%d/%m/%Y %H:%M:%S"))
library(datasets)
plot(power_table$DateTime,power_table$Sub_metering_1,type = "n",xlab="",ylab="Energy sub metering")
lines(power_table$DateTime,power_table$Sub_metering_1,col = "black" )
lines(power_table$DateTime,power_table$Sub_metering_2,col = "red" )
lines(power_table$DateTime,power_table$Sub_metering_3,col = "blue" )
legend("topright",lwd = 1, col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file = "plot3.png", width = 480, height = 480)
dev.off()