power_data <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date in ('1/2/2007','2/2/2007')", sep = ";")
power_table = data.table(power_data)
power_table$DateTime <- as.POSIXct( strptime(paste(power_table$Date, power_table$Time), format="%d/%m/%Y %H:%M:%S"))
library(datasets)
par(mfrow=c(2,2))
plot(power_table$DateTime,power_table$Global_active_power,type = "n",xlab="",ylab="Global Active Power")
lines(power_table$DateTime,power_table$Global_active_power)
plot(power_table$DateTime,power_table$Voltage,type = "n",xlab="datetime",ylab="Voltage")
lines(power_table$DateTime,power_table$Voltage)
plot(power_table$DateTime,power_table$Sub_metering_1,type = "n",xlab="",ylab="Energy sub metering")
lines(power_table$DateTime,power_table$Sub_metering_1,col = "black" )
lines(power_table$DateTime,power_table$Sub_metering_2,col = "red" )
lines(power_table$DateTime,power_table$Sub_metering_3,col = "blue" )
legend("topright",lwd = 1, bty = "n",cex=0.7,col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(power_table$DateTime,power_table$Global_reactive_power,type = "n",xlab="datetime",ylab="Global_reactive_power")
lines(power_table$DateTime,power_table$Global_reactive_power)
dev.copy(png,file = "plot4.png", width = 480, height = 480)
dev.off()